### ISSUE TITLE
zucchini is not running on mac os x 10.9

### ISSUE THREAD

**Issue by sandhyasujathasoman** [playup/zucchini#19]
i tried to run the demo project.But getting an error that 'm posting below

sandhyas-Mac-mini:zucchini-demo-master sandhya$ ZUCCHINI_DEVICE="iOS Simulator" zucchini run features/
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse': (<unknown>): mapping values are not allowed in this context at line 4 column 8 (Psych::SyntaxError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in`parse_stream'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:153:in `parse'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:129:in`load'
    from /Library/Ruby/Gems/2.0.0/gems/zucchini-ios-0.7.3/lib/zucchini/config.rb:12:in `base_path='
    from /Library/Ruby/Gems/2.0.0/gems/zucchini-ios-0.7.3/lib/zucchini/detector.rb:10:in`execute'
    from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.1/lib/clamp/command.rb:67:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.1/lib/clamp/subcommand/execution.rb:11:in`execute'
    from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.1/lib/clamp/command.rb:67:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.1/lib/clamp/command.rb:125:in`run'
    from /Library/Ruby/Gems/2.0.0/gems/zucchini-ios-0.7.3/bin/zucchini:15:in `<top (required)>'
    from /usr/bin/zucchini:23:in`load'
    from /usr/bin/zucchini:23:in `<main>'

Can any one please help me to resolve this problem.My ruby version is ruby 2.0.0. 'm trying it more than 2 days.Is this error is because of my mac os x10.9?? I have seen some sites saying that it will work only for mac os x10.6 and 10.7.

thanks in advance
sandhya

**Comment by aoopvn** [comment]
Can you try this where **"Simulator"** is the same as what you have in the config.yml 

``` bash
ZUCCHINI_DEVICE="Simulator" zucchini run features/
```
